package com.example.coinloreapi.models

data class ExchangesItems(
    var `0`: String? = null,
    var `1`: String? = null,
    var `10`: Any? = null,
    var `11`: Any? = null,
    var `12`: Any? = null,
    var `13`: String? = null,
    var `14`: Any? = null,
    var `2`: String? = null,
    var `3`: String? = null,
    var `4`: String? = null,
    var `5`: String? = null,
    var `6`: String? = null,
    var `7`: String? = null,
    var `8`: String? = null,
    var `9`: String? = null,
    var alexa: Any? = null,
    var auto: String? = null,
    var centralized: Any? = null,
    var country: String? = null,
    var date_added: String? = null,
    var date_live: String? = null,
    var dex: Any? = null,
    var f: String? = null,
    var fiat: String? = null,
    var id: String? = null,
    var mining: Any? = null,
    var name: String? = null,
    var name_id: String? = null,
    var pairs: Int? = null,
    var tr: Int? = null,
    var udate: String? = null,
    var url: String? = null,
    var usdt: String? = null,
    var volume_usd: Double? = null,
    var volume_usd_adj: Double? = null
)